# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'BonjourTool' do

end

target 'iosProvider' do
  platform :ios, '8.0'
  use_frameworks!
  pod "GCDWebServer", "~> 3.0"
end
